import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './ui/globals.css'
import SessionAuthProvider from '@/context/SessionAuthProvider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  icons: '/logo.png' ,
  title: 'AppTICMived',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='container'>
          <SessionAuthProvider>{children}</SessionAuthProvider>
          <ToastContainer />
        </main>
      </body>
    </html>
  )
}
